### ISSUE TITLE
error in enaml-native live-reloading  when executed with python3

### ISSUE THREAD

**Issue by rodgomesc** [codelv/enaml-native#62]
```
05-08 21:00:59.587  9009  9029 I pybridge: 
05-08 21:01:00.013  1409  1428 D hwcomposer: hw_composer sent 317 syncs in 60s
05-08 21:01:00.589  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:00.589  9009  9029 I pybridge: 
05-08 21:01:00.591  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:00.591  9009  9029 I pybridge: 
05-08 21:01:01.592  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:01.592  9009  9029 I pybridge: 
05-08 21:01:01.594  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:01.594  9009  9029 I pybridge: 
05-08 21:01:02.596  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:02.596  9009  9029 I pybridge: 
05-08 21:01:02.598  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:02.598  9009  9029 I pybridge: 
05-08 21:01:03.601  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:03.601  9009  9029 I pybridge: 
05-08 21:01:03.603  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:03.603  9009  9029 I pybridge: 
05-08 21:01:04.605  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:04.605  9009  9029 I pybridge: 
05-08 21:01:04.607  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:04.608  9009  9029 I pybridge: 
05-08 21:01:05.609  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:05.609  9009  9029 I pybridge: 
05-08 21:01:05.610  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:05.610  9009  9029 I pybridge: 
05-08 21:01:06.612  9009  9029 I pybridge: Dev client connecting ws://192.168.64.154:8888/dev...
05-08 21:01:06.612  9009  9029 I pybridge: 
05-08 21:01:06.614  9009  9029 I pybridge: Dev client connection dropped: concurrent.futures is required to use IOLoop.run_in_executor
05-08 21:01:06.614  9009  9029 I pybridge: 

```

**Comment by frmdstryr** [comment]
Can you try installing `pip-tornado`

**Comment by rodgomesc** [comment]
sr. I already installed pip-tornado, already compiled the most current version as well. 5.0.2, but without success so far

**Comment by rodgomesc** [comment]
and the environment.yml

```

name: faqui
bundle_id: com.faqui

# Channels to look for any specific libraries
channels:
  - codelv

# App dependencies to be installed
dependencies:
  - python
  - enaml-native

# Exclude unused packages and libs using glob patterns here.
# Only the ones required by enaml-native are left in by default.
# If you need to use a module (ex json) then remove lib._json.so
# from this list so it does not get exlcuded. You can also add specific
# exclusions under ios and android.
excluded:
  # Packages
  - idlelib
  - ensurepip
  - distutils
  - lib2to3
  - pydoc_data
  - hotshot
  - site-packages/enaml/qt
  - site-packages/enaml/workbench
  - site-packages/enaml/*lib
  - site-packages/enaml/scint*

  - lib._cod*
  - lib._element*
  - lib.cmath.so
  - lib.termios.so
  - lib._multi*
  - lib.mmap*
  - lib._hotshot.so
  #- lib._ssl.so
  - lib._sqlite3.so
  - lib.pyexpat.so
  - lib.strop.so
  - lib.syslog.so
  - lib.enaml.*ext.so
  #- lib._md5.so
  #- lib._sha*.so
  #- lib._json.so
  #- lib._csv.so
  #- lib.cPickle.so

# Android specific configuration
android:
  ndk: ~/Android/Sdk/ndk-bundle
  targets:
    - x86_64
    - x86
    - arm
    - arm64
  excluded:
    - lib._ctypes.so

# iOS specific configuration
ios:
  targets:
    - iphoneos
    - iphonesimulator
```
